settings_icon ="	//XCUIElementTypeStaticText[@name=\"Settings\"]"
bt_icon = "//XCUIElementTypeStaticText[@name=\"Bluetooth\"]"
bt_dut = "//XCUIElementTypeCell[@name=\"{}\"]"
bt_dut_text = "**/XCUIElementTypeStaticText[`label == \"{}\"`]"
forget_button = "//XCUIElementTypeStaticText[@name=\"FORGET_BUTTON\"]"
forget_confirm = "//XCUIElementTypeButton[@name=\"Forget Device\"]"
more_info_icon = "(//XCUIElementTypeButton[@name=\"More Info\"])"
settings_search =  "//XCUIElementTypeSearchField[@name=\"Search\"]"
DUT = "//XCUIElementTypeStaticText[@name=\"{}\"]"
pair = "//XCUIElementTypeButton[@name=\"Pair\"]"
pair_cancel = "//XCUIElementTypeButton[@name=\"Cancel\"]"
forget_device = "//XCUIElementTypeCell[@name=\"Forget this device\"]"
bt_toggle = "//XCUIElementTypeSwitch[@name=\"Bluetooth\"]"

#MBD App Locators(MacOS)
dashboard_text= "//XCUIElementTypeNavigationBar[@name=\"Microchip Bluetooth Data\"]"
#ble_uart_icon= "//XCUIElementTypeStaticText[@name=\"BLE UART\"]"
ble_uart_icon= "//XCUIElementTypeStaticText[@label=\"BLE UART\"]"
#device_scanner= "//XCUIElementTypeStaticText[@name=\"PIC32CXBZ\"]"
device_scanner= "//XCUIElementTypeStaticText[@label=\"PIC32CXBZ\"]"
#start_scan_button= "//XCUIElementTypeButton[@name=\"START\"]"
start_scan_button= "//XCUIElementTypeButton[@label=\"START\"]"
#text_view_place_holder = "//XCUIElementTypeStaticText[@name=\"{}\"]"
text_view_place_holder = "//XCUIElementTypeStaticText[@label=\"{}\"]"
#dut_name= "//XCUIElementTypeStaticText[@name='{}']"
dut_name= "//XCUIElementTypeStaticText[@label='{}']"
#back_button ="//XCUIElementTypeButton[@name=\"Back\"]"
back_button ="//XCUIElementTypeButton[@label=\"Back\"]"
#mbd_settings_icon = "//XCUIElementTypeButton[@name=\"BLE UART Config\"]"
mbd_settings_icon = "//XCUIElementTypeButton[@label=\"BLE UART Config\"]"
#change_mode_icon = "//XCUIElementTypeButton[@name=\"Change\"]"
change_mode_icon = "//XCUIElementTypeButton[@label=\"Change\"]"
demo_mode_checksum = "//XCUIElementTypeButton[@name=\"Checksum\"]"
#demo_mode_loopback = "//XCUIElementTypeButton[@name=\"Loopback\"]"
#demo_mode_loopback = "//XCUIElementTypeButton[@label=\"Loopback\"]"
demo_mode_loopback = "//XCUIElementTypeSheet[@label=\"alert\"]/XCUIElementTypeButton[2]"
demo_mode_fixed_pattern = "//XCUIElementTypeButton[@name=\"Fixed pattern\"]"
#demo_mode_uart = "//XCUIElementTypeButton[@name=\"UART\"]"
demo_mode_uart = "//XCUIElementTypeSheet[@label=\"alert\"]/XCUIElementTypeButton[3]"
#select_file = "//XCUIElementTypeButton[@name=\"Select\"]"
select_file = "//XCUIElementTypeButton[@label=\"Select\"]"
select_100K_file = "//XCUIElementTypeButton[@name=\"100k\"]"
#select_500K_file = "//XCUIElementTypeButton[@name=\"500k\"]"
#select_500K_file = "//XCUIElementTypeButton[@label=\"500k\"]"
select_1K_file = "//XCUIElementTypeSheet[@label=\"alert\"]/XCUIElementTypeButton[3]"
select_500K_file = "//XCUIElementTypeSheet[@label=\"alert\"]/XCUIElementTypeButton[5]"
TRCBP_icon = "//XCUIElementTypeButton[@name=\"TRCBP\"]"
#Done_icon = "//XCUIElementTypeButton[@name=\"Done\"]"
Done_icon = "//XCUIElementTypeButton[@label=\"Done\"]"
#confirm_modes = "//XCUIElementTypeStaticText[@name=\"BLE_Data_Path\"]"
confirm_modes = "//XCUIElementTypeStaticText[@label=\"BLE_Data_Path\"]"
#start_data_transfer = "//XCUIElementTypeButton[@name=\"START\"]"
start_data_transfer = "//XCUIElementTypeButton[@label=\"START\"]"
#stop_data_transfer = "//XCUIElementTypeButton[@name=\"STOP\"]"
stop_data_transfer = "//XCUIElementTypeButton[@label=\"STOP\"]"
#throughput_result_tx = "//XCUIElementTypeStaticText[@name=\"tx_throughput\"]"
throughput_result_tx = "//XCUIElementTypeStaticText[@label=\"tx_throughput\"]"
#throughput_result_rx = "//XCUIElementTypeStaticText[@name=\"rx_throughput\"]"
throughput_result_rx = "//XCUIElementTypeStaticText[@label=\"rx_throughput\"]"
#logmessage = "//XCUIElementTypeTextView[@name=\"BLE_UART_Log\"]"
logmessage = "//XCUIElementTypeTextView[@label=\"BLE_UART_Log\"]"
#clear_text = "//XCUIElementTypeStaticText[@name=\"Clear\"]"
clear_text = "//XCUIElementTypeStaticText[@label=\"Clear\"]"
#raw_data_icon = "//XCUIElementTypeButton[@name=\"Text mode\"]"
raw_data_icon = "//XCUIElementTypeButton[@label=\"Text mode\"]"
burst_mode_icon = "//XCUIElementTypeButton[@name=\"Burst mode\"]"
confirm_raw_data_trcbp = "///XCUIElementTypeStaticText[@label=\"UART,Profile : TRCBP\"]"
confirm_raw_data_trp = "//XCUIElementTypeStaticText[@label=\"UART,Profile : TRP\"]"
raw_data_loopback_confirm_trp = "//XCUIElementTypeStaticText[@label=\"Loopback,Profile : TRP\"]"
raw_data_loopback_confirm_trcbp = "//XCUIElementTypeStaticText[@label=\"Loopback,Profile : TRCBP\"]"
raw_text_field = "//XCUIElementTypeTextField[@name=\"Input_string\"]"
raw_data_log_message = "//XCUIElementTypeTextView[@name=\"app_log\"]"
raw_clear_text = "//XCUIElementTypeStaticText[@name=\"Clear\"]"
raw_data_uart_confirm_trp = "//XCUIElementTypeStaticText[@label=\"UART,Profile : TRP\"]"
raw_data_uart_confirm_trcbp = "//XCUIElementTypeStaticText[@label=\"UART,Profile : TRCBP\"]"
write_with_response_icon = "//XCUIElementTypeButton[@name=\"Write with Response\"]"
device_info = "//XCUIElementTypeOther[@name=\"Device Information\"]"
firmware_version = "//XCUIElementTypeStaticText[@name=\"fwVersion\"]"
scan_button = "//XCUIElementTypeButton[@name=\"Scan\"]"
ota_scan_button = "//XCUIElementTypeButton[@name=\"SCAN\"]"
receive_data_timeout_button = "//XCUIElementTypeStaticText[@name=\"Multilink configuration\"]"
set_timeout_button = "//XCUIElementTypeButton[@name=\"Set timeout value\"]"
set_timeout_field = "//XCUIElementTypeButton[@name=\"{}\"]"

'''
#MBD App Locators(iOS)
dashboard_text= "//XCUIElementTypeNavigationBar[@name=\"Microchip Bluetooth Data\"]"
ble_uart_icon= "//XCUIElementTypeStaticText[@name=\"BLE UART\"]"
device_scanner= "//XCUIElementTypeStaticText[@name=\"PIC32CXBZ\"]"
start_scan_button= "//XCUIElementTypeButton[@name=\"START\"]"
text_view_place_holder = "//XCUIElementTypeStaticText[@name=\"{}\"]"
dut_name= "//XCUIElementTypeStaticText[@name='{}']"
back_button ="//XCUIElementTypeButton[@name=\"Back\"]"
mbd_settings_icon = "//XCUIElementTypeButton[@name=\"BLE UART Config\"]"
change_mode_icon = "//XCUIElementTypeButton[@name=\"Change\"]"
demo_mode_checksum = "//XCUIElementTypeButton[@name=\"Checksum\"]"
demo_mode_loopback = "//XCUIElementTypeButton[@name=\"Loopback\"]"
demo_mode_fixed_pattern = "//XCUIElementTypeButton[@name=\"Fixed pattern\"]"
demo_mode_uart = "//XCUIElementTypeButton[@name=\"UART\"]"
select_file = "//XCUIElementTypeButton[@name=\"Select\"]"
select_100K_file = "//XCUIElementTypeButton[@name=\"100k\"]"
select_500K_file = "//XCUIElementTypeButton[@name=\"500k\"]"
select_1K_file = "//XCUIElementTypeButton[@name=\"1k\"]"
TRCBP_icon = "//XCUIElementTypeButton[@name=\"TRCBP\"]"
Done_icon = "//XCUIElementTypeButton[@name=\"Done\"]"
confirm_modes = "//XCUIElementTypeStaticText[@name=\"BLE_Data_Path\"]"
start_data_transfer = "//XCUIElementTypeButton[@name=\"START\"]"
stop_data_transfer = "//XCUIElementTypeButton[@name=\"STOP\"]"
throughput_result_tx = "//XCUIElementTypeStaticText[@name=\"tx_throughput\"]"
throughput_result_rx = "//XCUIElementTypeStaticText[@name=\"rx_throughput\"]"
logmessage = "//XCUIElementTypeTextView[@name=\"BLE_UART_Log\"]"
clear_text = "//XCUIElementTypeStaticText[@name=\"Clear\"]"
raw_data_icon = "//XCUIElementTypeButton[@name=\"Text mode\"]"
burst_mode_icon = "//XCUIElementTypeButton[@name=\"Burst mode\"]"
confirm_raw_data_trcbp = "///XCUIElementTypeStaticText[@label=\"UART,Profile : TRCBP\"]"
confirm_raw_data_trp = "//XCUIElementTypeStaticText[@label=\"UART,Profile : TRP\"]"
raw_data_loopback_confirm_trp = "//XCUIElementTypeStaticText[@label=\"Loopback,Profile : TRP\"]"
raw_data_loopback_confirm_trcbp = "//XCUIElementTypeStaticText[@label=\"Loopback,Profile : TRCBP\"]"
raw_text_field = "//XCUIElementTypeTextField[@name=\"Input_string\"]"
raw_data_log_message = "//XCUIElementTypeTextView[@name=\"app_log\"]"
raw_clear_text = "//XCUIElementTypeStaticText[@name=\"Clear\"]"
raw_data_uart_confirm_trp = "//XCUIElementTypeStaticText[@label=\"UART,Profile : TRP\"]"
raw_data_uart_confirm_trcbp = "//XCUIElementTypeStaticText[@label=\"UART,Profile : TRCBP\"]"
write_with_response_icon = "//XCUIElementTypeButton[@name=\"Write with Response\"]"
device_info = "//XCUIElementTypeOther[@name=\"Device Information\"]"
firmware_version = "//XCUIElementTypeStaticText[@name=\"fwVersion\"]"
scan_button = "//XCUIElementTypeButton[@name=\"Scan\"]"
ota_scan_button = "//XCUIElementTypeButton[@name=\"SCAN\"]"
receive_data_timeout_button = "//XCUIElementTypeStaticText[@name=\"Multilink configuration\"]"
set_timeout_button = "//XCUIElementTypeButton[@name=\"Set timeout value\"]"
set_timeout_field = "//XCUIElementTypeButton[@name=\"{}\"]"
'''
ble_ota_icon="//XCUIElementTypeStaticText[@name=\"OTA DFU\"]"
ota_select_image = "//XCUIElementTypeButton[@name=\"Select Image\"]"
ota_fw_binfile1 = "//XCUIElementTypeStaticText[@name=\"{}\"]"
ota_fw_binfile2 = "//XCUIElementTypeStaticText[@name=\"{}\"]"
ota_fw_binfile3 = "//XCUIElementTypeStaticText[@name=\"{}\"]"
ota_current_version = "//XCUIElementTypeStaticText[contains(@label,\"Current version : \")]"
ota_current_version_no = "//XCUIElementTypeStaticText[@name=\"{}\"]"
ota_update_version = "//XCUIElementTypeStaticText[contains(@label,\"Update version : \")]"
ota_update_version_no = "//XCUIElementTypeStaticText[@name=\"{}\"]"
ok_button = "//XCUIElementTypeButton[@name=\"Ok\"]"
ota_update_success = "//XCUIElementTypeStaticText[@name=\"OTA update successfully\"]"
ota_fw_version =  "//XCUIElementTypeStaticText[contains(@label,\"Update version = \")]"
ota_bt_off = ""
ota_bt_is_off = ""
ota_error = "//XCUIElementTypeStaticText[@name=\"BLE disconnect or BT Off\"]"
ota_Command_error = "//XCUIElementTypeStaticText[@name=\"Request is not accepted\"]"
ota_Command_error_2 = "//XCUIElementTypeStaticText[@name=\"Invalid image size\"]"
ota_pairing_fail = "//XCUIElementTypeStaticText[@name=\"BLE disconnect or BT Off\"]"
back_to_main_page = "//XCUIElementTypeButton[@name=\"Microchip Bluetooth Data\"]"

