settings_icon ="	//XCUIElementTypeStaticText[@name=\"Settings\"]"
bt_icon = "//XCUIElementTypeStaticText[@name=\"Bluetooth\"]"
bt_dut = "//XCUIElementTypeCell[@name=\"{}\"]"
bt_dut_text = "**/XCUIElementTypeStaticText[`label == \"{}\"`]"
forget_button = "//XCUIElementTypeStaticText[@name=\"FORGET_BUTTON\"]"
forget_confirm = "//XCUIElementTypeButton[@name=\"Forget Device\"]"
more_info_icon = "(//XCUIElementTypeButton[@name=\"More Info\"])"
settings_search =  "//XCUIElementTypeSearchField[@name=\"Search\"]"
DUT = "//XCUIElementTypeStaticText[@name=\"{}\"]"
pair = "//XCUIElementTypeButton[@name=\"Pair\"]"
forget_device = "//XCUIElementTypeCell[@name=\"Forget this device\"]"
bt_toggle = "//XCUIElementTypeSwitch[@name=\"Bluetooth\"]"

#MBD App Locators

dashboard_text= "//XCUIElementTypeNavigationBar[@name=\"Microchip Bluetooth Data\"]"
ble_uart_icon= "//XCUIElementTypeStaticText[@name=\"BLE UART\"]"
device_scanner= "//XCUIElementTypeStaticText[@name=\"PIC32CXBZ\"]"
ble_uart_scanner = "//XCUIElementTypeStaticText[@name=\"PIC32CXBZ\"]"
start_scan_button= "//XCUIElementTypeButton[@name=\"START\"]"
scan_button= "//XCUIElementTypeButton[@name=\"START\"]"
text_view_place_holder = "//XCUIElementTypeStaticText[@name=\"{}\"]"
dut_name= "//XCUIElementTypeStaticText[@name='{}']"
back_button ="//XCUIElementTypeButton[@name=\"Back\"]"
mbd_settings_icon = "//XCUIElementTypeButton[@name=\"BLE UART Config\"]"
change_mode_icon = "//XCUIElementTypeButton[@name=\"Change\"]"
demo_mode_checksum = "//XCUIElementTypeButton[@name=\"Checksum\"]"
demo_mode_loopback = "//XCUIElementTypeButton[@name=\"Loopback\"]"
demo_mode_fixed_pattern = "//XCUIElementTypeButton[@name=\"Fixed pattern\"]"
demo_mode_uart = "//XCUIElementTypeButton[@name=\"UART\"]"
select_file = "//XCUIElementTypeButton[@name=\"Select\"]"
select_100K_file = "//XCUIElementTypeButton[@name=\"100k\"]"
select_500K_file = "//XCUIElementTypeButton[@name=\"500k\"]"
TRCBP_icon = "//XCUIElementTypeButton[@name=\"TRCBP\"]"
Done_icon = "//XCUIElementTypeButton[@name=\"Done\"]"
confirm_modes = "//XCUIElementTypeStaticText[@name=\"BLE_Data_Path\"]"
start_data_transfer = "//XCUIElementTypeButton[@name=\"START\"]"
stop_data_transfer = "//XCUIElementTypeButton[@name=\"STOP\"]"
throughput_result_tx = "//XCUIElementTypeStaticText[@name=\"tx_throughput\"]"
throughput_result_rx = "//XCUIElementTypeStaticText[@name=\"rx_throughput\"]"
logmessage = "//XCUIElementTypeTextView[@name=\"BLE_UART_Log\"]"
clear_text = "//XCUIElementTypeStaticText[@name=\"Clear\"]"
raw_data_icon = "//XCUIElementTypeButton[@name=\"Text mode\"]"
burst_mode_icon = "//XCUIElementTypeButton[@name=\"Burst mode\"]"
confirm_raw_data_trcbp = "///XCUIElementTypeStaticText[@label=\"UART,Profile : TRCBP\"]"
confirm_raw_data_trp = "//XCUIElementTypeStaticText[@label=\"UART,Profile : TRP\"]"
raw_data_loopback_confirm_trp = "//XCUIElementTypeStaticText[@label=\"Loopback ,Profile : TRP\"]"
raw_data_loopback_confirm_trcbp = "//XCUIElementTypeStaticText[@label=\"Loopback ,Profile : TRCBP\"]"
raw_text_field = "//XCUIElementTypeTextField[@name=\"Input_string\"]"
raw_data_log_message = "//XCUIElementTypeTextView[@name=\"app_log\"]"
raw_clear_text = "//XCUIElementTypeStaticText[@name=\"Clear\"]"
raw_data_uart_confirm_trp = "//XCUIElementTypeStaticText[@label=\"UART,Profile : TRP\"]"
raw_data_uart_confirm_trcbp = "//XCUIElementTypeStaticText[@label=\"UART,Profile : TRCBP\"]"
write_with_response_icon = "//XCUIElementTypeButton[@name=\"Write with Response\"]"
device_info = "//XCUIElementTypeOther[@name=\"Device Information\"]"
firmware_version = "//XCUIElementTypeStaticText[@name=\"fwVersion\"]"




